phraseapp:
  access_token: 95dbbf1d0bdf587582a64b635dc1738edfd4b7feb6a0f3633ff35fef5f462252
  project_id: 8e1da11a577bc4eb2ca0a2b4011d165d
  push:
    sources:
    - file: airmapsdk/src/main/res/values/androidstrings.xml #android only
      params:
        tags: "android"
        file_format: xml
        locale_id: en
  pull:
    targets:
    - file: airmapsdk/src/main/res/values-<locale_code>/translated-strings.xml
      params:
        tag: "ios"
        file_format: xml
        convert_emoji: true
        format_options: 
          convert_placeholder: true
          escape_linebreaks: true

    - file: airmapsdk/src/main/res/values-<locale_code>/androidstrings.xml #android only
      params:
        tag: "android"
        file_format: xml
        convert_emoji: true
        format_options:
          convert_placeholder: true
          escape_linebreaks: true
